### ISSUE TITLE
namespace.addObject() doesn't work

### ISSUE THREAD

**Issue by PManlio** [PManlio/industrialinformaticsproj#1]
Nel codice, in server/server.js è stato messo un tag `@error` nella posizione della funzione `let build_my_address_space = (server) => { ... }`

Gli errori che vengono lanciati sono:
```
/home/manlio/Scrivania/industrialinformaticsproj/server/node_modules/node-opcua-address-space/dist/src/address_space.js:1067
                throw err;
                ^

Error
    at Object.assert (/home/manlio/Scrivania/industrialinformaticsproj/server/node_modules/node-opcua-assert/dist/index.js:13:21)
    at addressSpace.modelChangeTransaction (/home/manlio/Scrivania/industrialinformaticsproj/server/node_modules/node-opcua-address-space/dist/src/namespace.js:487:37)
    at AddressSpace.modelChangeTransaction (/home/manlio/Scrivania/industrialinformaticsproj/server/node_modules/node-opcua-address-space/dist/src/address_space.js:1064:17)
    at UANamespace.createNode (/home/manlio/Scrivania/industrialinformaticsproj/server/node_modules/node-opcua-address-space/dist/src/namespace.js:486:26)
    at UANamespace.addObject (/home/manlio/Scrivania/industrialinformaticsproj/server/node_modules/node-opcua-address-space/dist/src/namespace.js:337:30)
    at build_my_address_space (/home/manlio/Scrivania/industrialinformaticsproj/server/server.js:24:28)
    at server.initialize (/home/manlio/Scrivania/industrialinformaticsproj/server/server.js:55:5)
    at Immediate.setImmediate (/home/manlio/Scrivania/industrialinformaticsproj/server/node_modules/node-opcua-server/dist/opcua_server.js:591:25)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
```

Possibile bugfix è testare il server su ubuntu 18.04 e su Windows, perché ho già avuto problemi con Ubuntu 19.04 per `npm i node-opcua` , in cui è stato necessario installare anche `npm i source-map-support`

**Comment by PManlio** [comment]
Na scemenza, al posto di `browseName` avevo scritto `browseRName`, sono abbastanza rincoglionito
